name: simple-framework-starter
recipe: lamp
config:
  php: '7.4'
  database: mysql
  xdebug: 'develop,debug'
services:
  appserver:
    build:
      - composer install
    config:
      php: ./.lando.config/php.ini
  database:
    portforward: 3307